edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
unstable_features = true
use_field_init_shorthand = true
version = "Two"
