name: 🧪 Check

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: "always"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  check:
    name: 🧪 Check
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: ⚡️ Install additional nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: ⚡️ Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: ⚡️ Shared Compilation Cache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: 🧪 Install coverage tools
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: 🧪 Test
        run: |
          cargo +stable llvm-cov --lib --all-features --workspace --codecov --output-path=codecov.json
          cargo +nightly llvm-cov --doc --all-features --workspace --codecov --output-path=codecov-doctests.json

      - name: 📤 Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: codecov.json,codecov-doctests.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 💬 Clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: -- -Dwarnings
          reporter: github-check
        continue-on-error: true
